# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Watooka Films | Caribbean Dreams to
email: info@watookafilms.com
description: >- # this means to ignore newlines until "baseurl:"
  Film and Television Production, Original Content, Location Fixer, Production Management, Creative Consulting, Directing Services, Director, Cinemeatography, Production Services, Jamaica, Caribbean
#Advanced Settings 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://watookafilms.com" # the base hostname & protocol for your site, e.g. http://example.com
language: en

# Build settings
markdown: kramdown
remote_theme: Watooka-Films/jekflix-watooka
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: true
show_get_theme_btn: false

#Settings
show_hero: true


#Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate-content

#Menu
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Services
    url: /services
  - title: Feed
    url: /feed.xml

#Social Media
twitter_username: watookafilms
instagram_username: watookafilms
linkedin_username: company/watookafilms

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
